name: Docker pipeline

on:
  push:
    branches:
      - LAB2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t pasha ./LAB2

      - name: Push image to Docker Hub
        run: docker push pasha

      - name: Run tests in Docker container
        run: docker run pasha
